### PR TITLE
Add Markdown-It for LaTeX Support, Replace Snarkdown

### LINKED ISSUE #22: Incorrect numbering in ordered lists
Numbered lists don't go higher than 1. Also spacing between is off.

Example:
image

### LINKED ISSUE #107: Multiline formatting of code block is lost for several (non-supported?) languages
For example, the `assembly`/`nasm`/`x86` code block lost its formatting and shown as single line.

image

The corresponding JSON of the response:
```json
    {
      "role": "assistant",
      "content": "Here's a simple \"Hello, World!\" program in x86 assembly language for the NASM (Netwide Assembler) assembler:\n\n```nasm\nsection .data\n    msg db 'Hello, World!', 0\n\nsection .text\n    global _start\n\n_start:\n    ; Print the message\n    mov eax, 4      ; system call number for write\n    mov ebx, 1      ; file descriptor (stdout)\n    mov ecx, msg    ; address of string to write\n    mov edx, len    ; length of string\n    int 0x80        ; invoke operating system\n\n    ; Exit the program\n    mov eax, 1      ; system call number for exit\n    xor ebx, ebx    ; return code (0)\n    int 0x80        ; invoke operating system\n\nsection .data\nlen equ $-msg    ; calculate length of string\n```\n\n...."
    },
```

Another examples:

image
image

And again, a lot of `\n` in original responce are lost in code block.

### PR DESCRIPTION
**Pull request by Anajrim01**
### Overview

This PR introduces the usage of `markdown-it` with a custom LaTeX plugin to replace the use of `snarkdown`. The goal is to add robust support for LaTeX rendering directly from the API, ensuring that both inline and block LaTeX expressions are correctly parsed and displayed.

### Changes
<details>
<summary>Click me</summary>

- **Markdown-It Integration**
  - Integrated `markdown-it` with `markdown-it-katex` for Markdown parsing.
  - Added a custom LaTeX plugin to handle both inline (`\( ... \)`) and block (`\[ ... \]`) LaTeX expressions.
  - Added a custom LaTeX plugin to handle both inline (`$`) and block (`$$`) LaTeX expressions.
  
- **Removed Snarkdown**
  - Removed outdated `snarkdown` library from the project.
  
- **Updated Components**
  - Refactored Svelte components to use the new `renderMarkdown` utility from `markdownKatex.ts`, leveraging `markdown-it` with LaTeX support.

### LaTeX Support

- **Inline LaTeX**
  - Inline LaTeX expressions are now handled between `\( ... \)` or/and `$`.
  
- **Block LaTeX**
  - Block LaTeX expressions are managed between `\[ ... \]`  or/and `$$`.

### Impact

This migration from `snarkdown` to `markdown-it` with custom LaTeX support will ensure that LaTeX from the API is correctly parsed and displayed, enhancing the readability and usability of mathematical content within the application.

</details>

### Features

- ✅ Robust LaTeX support for both inline and block expressions.
- ✅ Improved and consistent Markdown rendering with `markdown-it`.

### To-Do

- [x] Replace all instances of `snarkdown` with `markdown-it`.
- [x] Implement the new `markdownKatex.ts` utility.
- [x] Ensure all Svelte components use `renderMarkdown` for content rendering.
- [x] Verify rendering consistency across all relevant parts of the application.
- [x] Additional testing and validation ~~(I don't have the ability to test this live).~~
- [ ] Update readme to reflect changes (if applicable and wanted).

### Example Before and After
<details>
<summary>Click me</summary>

#### Before (Using `snarkdown`):
```svelte
<script lang="ts">
    import snarkdown from 'snarkdown';
    // Other imports...
</script>

<!-- Usage in component -->
<p>{@html snarkdown(chat.contextMessage.content)}</p>
```

image

#### After (Using `markdown-it` with LaTex support):
```svelte
<script lang="ts">
    import { renderMarkdown } from '$misc/markdownKatex';
    // Other imports...
</script>

<!-- Usage in component -->
<p>{@html renderMarkdown(chat.contextMessage.content)}</p>
```
image
</details>

This change ensures a more robust and extensible foundation for future enhancements and provides a richer user experience with LaTeX support in Markdown content. 

### Sideeffect Fixes:
As a side-effect, using this newer library adds support for more highlight and correct colors being used in languages.

Kind of fixes #107 but doesn't put in a proper code block, looks like this after changes (before can be seen in the issue):

<details>
<summary>After Image</summary>

image

</details>

This PR also fixed #22, due to the newer updated formatter it correctly parses the numerical list.

### CODE REVIEW

**Comment by Anajrim01** [comment]
As a side-effect, using this newer library adds support for more highlight and correct colors being used in languages.

**Comment by Shackless** [comment]
@Anajrim01 great work, thank you! 

The only nitpick I have is that there are now a lot of warnings like these in the console: 

CleanShot 2024-09-11 at 08 42 25

I think I called the hljs functions way too often before because otherwise it wouldn't work properly with snarkdown. Would you mind taking a look at this? If they can't be resolved easily, I'm also fine with that and will merge your PR anyways as your solution is clearly better.

**Comment by Anajrim01** [comment]
I'll resolve these warnings asap.

**Comment by Anajrim01** [comment]
@Shackless Alright, I've resolved the warnings now. Now the code is only highlighted once instead of it trying to highlight it over and over again 😄.

**Review by Shackless — APPROVED** [review]

**Pull request merged**
