### PR TITLE
Image Uploads, Markdown Styling, and Migration to IndexedDb

### LINKED ISSUE #77: GPT-4-vision-preview support
Is there any plans currently to support the new GPT-4-vision model in the future for uploading images in chats?

### LINKED ISSUE #123: Chat title is being auto-updated again after a refresh
I've encountered a bug where the chat title gets auto-updated again after a window refresh. This issue appears to have been introduced in #111. Currently, after setting a title, if you refresh the window and send another message, the chat title gets updated again unexpectedly.

**Steps to Reproduce:**

1. Set a chat title.
2. Refresh the window.
3. Send another message.
4. Observe the chat title being updated again.

**Expected Behavior:**

The chat title should remain as initially set even after a window refresh and subsequent messages should not auto-update the title.

**Actual Behavior:**

After setting a chat title and refreshing the window, sending another message causes the chat title to be updated again.

**Root Cause:**

The issue stems from the `hasUpdatedTitle` flag being stored locally in the context of the window. This local storage is reset after a window refresh.

**Proposed Solution:**

Store the `hasUpdatedTitle` flag in `localStorage` instead of within the window context to preserve the state across refreshes.

This issue has been addressed in #118

### LINKED ISSUE #124: Paragraphs isn't properly displayed
**Description:**
It has been observed that paragraphs are not being displayed correctly in SlickGPT. The text appears to be running together without proper paragraph breaks, which impacts readability and user experience.

**Steps to Reproduce:**
1. Open SlickGPT.
2. Ask for a any multi-paragraph text.
3. Observe the output.

**Expected Result:**
The output should display the text with proper paragraph breaks, maintaining the format of the input/output text.

**Actual Result:**
All paragraphs are displayed in a single block without clear separation between them.

### LINKED ISSUE #127: Tables Not Displayed Properly Due to Missing CSS Styling
Tables provided in chatbot responses are not being displayed as intended. The main issues appear to stem from the lack of proper CSS styling, which results in the following problems:

1. **Borders**: Borders around table cells are either missing or inconsistent, making it hard to distinguish various rows and columns.
2. **Spacing & Padding**: Inadequate spacing and padding within table cells, affecting content readability.
3. **Alignment**: Text and content within the table cells are not properly aligned, creating a cluttered look.
4. **Responsive Design**: Tables do not adapt well to different screen sizes within the chatbot interface, causing horizontal scrolling or overflow issues on smaller devices.
5. **Styling Consistency**: Different tables across various chatbot interactions lack a consistent style, leading to a non-uniform user interface.

**Steps to Reproduce:**
1. Engage with the chatbot and prompt a response that includes a table (e.g., ask for a report, user data, etc.).
2. Observe the presentation of the table in the chatbot's response and note any issues with borders, spacing, and alignment.

**Expected Behavior:**
Tables in chatbot responses should have a clean and consistent appearance with:
- Clearly defined borders around cells.
- Appropriate padding and spacing for better readability.
- Uniform alignment of content within cells.
- Responsive design adjustments ensuring that tables are viewable on all devices and screen sizes within the chatbot interface.
- Consistent styling across all tables in different chatbot interactions.

**Screenshots:**
image

**Relevant Context:**
- This issue affects the overall user experience by making the table data difficult to read and interpret.
- Proper table styling is crucial for the usability of data-rich chatbot responses.

**Proposed Solution:**
- Implement or update the CSS styles applied to chatbot tables to include appropriate styling rules.
- Define consistent CSS classes for table elements to ensure a uniform appearance across all chatbot interactions.
- Add media queries or equivalent styling solutions to address responsive design issues, making sure tables adapt well to different screen sizes in the chatbot interface.

### PR DESCRIPTION
**Pull request by Anajrim01**
This PR introduces a new feature enabling users to upload images alongside text messages in the chat application. Additionally, it fixes a few bugs related to markdown rendering. The following key changes have been made:

- **IndexedDB**: Switched from localStorage which has a limit of 5mb to IndexedDB.
- **File Uploads**: Added functionality to handle image file uploads and convert them to base64 format.
- **Chat Message Structure**: Updated the ChatMessage interface to support both text and image content, including image URLs and filenames.
- **Submit Function**: Modified the handleSubmit function to handle both text and image content, including images in the payload.
- **Tokenization**: Updated tokenization logic to correctly count tokens for both text and image content formats.
- **Code Quality**: Improved code readability and maintainability with descriptive variable names.
- **Backward Compatibility**: Ensured backward compatibility with existing text-only messages.
- **Drag-and-Drop Fix**: Fixed the drag-and-drop issue with description parsing in chat actions.
- **Bug Fix**: Fixed an issue (introduced in #111) where the title would be incorrectly updated after setting it, refreshing the window, and sending another message. The flag `hasUpdatedTitle` is now stored in local storage to persist across window refreshes.
- **Bug Fix**: Fixed an issue where the paragraph and tables wasn't properly displayed.
- **CSS Styling for Markdown**: Applied proper CSS styling to markdown, utilizing Tailwind CSS for a consistent and clean look.

## TODO
- [x] Add support for image filenames without including them in the final payload.
- [x] Cost calculation for images.
- [x] Limit uploads to a maximum of 10 in one prompt.
- [x] Add logic to fetch dimensions of image.
- [x] ~Ensure that the feature is only available for users using OpenAI or those on the Pro plan (or something).~ Works with LLM's which support *Vision* too.
- [x] Refactor
- [x] Testing

### User Interface Change
- [x] Fix UI and placement to ensure a seamless user experience (help needed).
- [x] Show user attachment in UI.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Maintainer Changes
- [x] Make corresponding changes to the documentation
- [x] SlickGPT Pro - maintainer needs to update proxy to support images as content
- [ ] Add support for image URLs (user interface change).
- [ ] Let user decide image resolution (detail).

## Related Issues
Closes #77 
Fixes #123 
Fixes #124 
Fixes #127

### CODE REVIEW

**Comment by Anajrim01** [comment]
Hello @Shackless, 

I'm not sure how I'll be moving forward with adding image url support and letting user choose between low/high/auto (currently default to high).

Excluding that, what's left is the refactoring and you updating the SlickGPT Pro middleware to support image uploads.

Regarding the excluded features, I'd love your assistance in implementing it, and maybe even changing up the button for the image upload to some place else. I'm not sure about it yet, would love some help/feedback on it.

**Comment by Shackless** [comment]
@Anajrim01 Thank you! I'll take over as soon as I can find the time.

**Review by Anajrim01 — COMMENTED** [review]
switch to async instead of promises to avoid nested `then` and improve readability.

**Comment by Anajrim01** [comment]
What needs to be tested:
- Firebase support
- Overall functionality with Pro.

I've reviewed the code, and I don't see any major issues with the code which come up to me directly.

**Review by Shackless — APPROVED** [review]

**Pull request merged**
